### ISSUE TITLE
Support Contract protocol

### ISSUE THREAD

**Issue by igorkamyshev** [movpushmov/effector-reform#2]
Now, any `AsyncValidationFn` could be used as a validator. You can allow passing [`Contract`](https://withease.pages.dev/protocols/contract.html) to this field. It would allow users of this lib to use any integration (the full list can be found in [docs](https://withease.pages.dev/protocols/contract.html)).

**Comment by movpushmov** [comment]
Now effector-reform support contracts! 23129a7c19f5dd0290c073fad206645c098f37c1
